server {
    listen 80;
    listen [::]:80;

    server_name infra.194-226-49-20.sslip.io;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name infra.194-226-49-20.sslip.io;

    ssl_certificate /etc/letsencrypt/live/infra.194-226-49-20.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/infra.194-226-49-20.sslip.io/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html/mywebsite;
    index index.html;

    location = /mywebsite {
        return 301 /;
    }

    location = /mywebsite/ {
        return 301 /;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
}
